name: WebDemoShop UI Testing
on:
  push:
    paths:
    - 'cypress/e2e/1-web-ui-testing/'
jobs:
  cypress-run:
    name: WebDemoShop UI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regression Webdemoshop UI
        uses: cypress-io/github-action@v6
        with:
          spec: |
            cypress/e2e/1-web-ui-testing/